spring:
  r2dbc:
    url: r2dbc:h2:mem:///~/db/
    name: testdb
    username: sa
    password:

#spring:
#  r2dbc:
#    url: r2dbc:mysql://localhost:3306
#    name: docker_db
#    username: root
#    password: root
#    pool:
#      initial-size: 10
#      max-size: 30
#      max-idle-time: 15s
#      validation-query: SELECT 1
#    properties:
#      connect-timeout: 10
#      ssl: false
#      max-create-connection-time: 3
#      max-acquire-time: 5
#      max-life-time: 15

logging:
  level:
    org:
      hibernate:
        nodeValue: ERROR
        SQL: DEBUG
      springframework:
        web: DEBUG